docs_dir: docs
markdown_extensions:
- admonition
pages:
- 项目详情: 项目详情.md
- 前期准备: 前期准备.md
- 工具使用: 工具使用.md
- 资源规范: 资源规范.md
- 代码规范: 代码规范.md
- API:
  - TestChild: api\scene1\Node2D.md
repo_url: https://github.com/vmjcv/sunset/
site_name: SunSet
theme: material
